server:
  port: 8080

spring:
  datasource:
    username: root
    password: Brabus270194
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
      show-sql: true

indexing-settings:
  sites:
#    - url: https://www.playback.ru/
#      name: PlayBack.Ru
    - url: https://www.svetlovka.ru/
      name: Svetlovka.ru
#    - url: https://dombulgakova.ru/
#      name: DomBulgakova.ru
#    - url: https://domotekhnika.ru/
#      name: Domotekhnika.ru

